[package]
name = "clash-lite"
version = "0.0.3"
edition = "2024"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tray-icon = "0.26.1"
ureq = { version = "3.4.2", default-features = false, features = ["rustls", "gzip", "json"] }
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_System_DataExchange", "Win32_System_Memory", "Win32_System_Registry", "Win32_Networking_WinInet", "Win32_System_Threading", "Win32_Security", "Win32_UI_Shell", "Win32_System_JobObjects"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
